Repository AY2324S2-CS2103T-F10-1/tp, pull requests merged in 2024-04, with the labels that each got.

#65 Add new color scheme for NAB
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NabTheme.css
Labels: priority.Low

#66 Change UG for Add Command to allow optional remarks
  docs/UserGuide.md
Labels: type.Documentation

#68 Add resizable functionality to result window
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.Low

#87 Edit Add and Edit feature to include remarks, remove Remarks portion
  docs/UserGuide.md
Labels: type.Documentation

#85 Fix list
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
Labels: severity.Medium

#73 Update User Guide
  docs/UserGuide.md
Labels: type.Documentation

#91 Fix dates
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/AdmissionDate.java
  src/main/java/seedu/address/model/person/Dob.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AdmissionDateTest.java
  src/test/java/seedu/address/model/person/DobTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: severity.Medium

#92 Add remarks parameter to command summary
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/Ui.png
  src/main/java/seedu/address/logic/Messages.java
Labels: type.Documentation
